export const dashBoardActionTypes = {
    FETCH_ASSIGNMENST_DATA: 'FETCH_ASSIGNMENST_DATA',
    FETCH_IN_ACTIVE_ASSIGNMENST_DATA: 'FETCH_IN_ACTIVE_ASSIGNMENST_DATA',
    FETCH_VISIT_STATUS: 'FETCH_VISIT_STATUS',
    FETCH_TIMESHEET_PENDING_APROVAL: 'FETCH_TIMESHEET_PENDING_APROVAL',
    FETCH_CONTRACTS_NEAR_EXPIRY: 'FETCH_CONTRACTS_NEAR_EXPIRY',
    FETCH_DOCUMENT_APROVAL: 'FETCH_DOCUMENT_APROVAL',
    FETCH_BUDGET_MONETARY: 'FETCH_BUDGET_MONETARY',
    FETCH_BUDGET_HOURS: 'FETCH_BUDGET_HOURS',
    FETCH_DOCUMENTATION_APPROVAL: 'FETCH_DOCUMENTATION_APPROVAL',
    TOGGLE_ALL_COORDINATOR: 'TOGGLE_ALL_COORDINATOR',
    INACTIVE_ASSIGNMENT_COUNT: 'INACTIVE_ASSIGNMENT_COUNT',
    FETCH_DASHBOARD_COUNT: 'FETCH_DASHBOARD_COUNT',
    CLEAR_DASHBOARD_REDUCER: 'CLEAR_DASHBOARD_REDUCER',
    SELECTED_DOCUMENT_TO_APPROVE: 'SELECTED_DOCUMENT_TO_APPROVE'
};

export const appLayoutActionTypes = {
    FETCH_COMPANY_LIST: 'FETCH_COMPANY_LIST',
    UPADTE_SELECTED_COMPANY: "UPADTE_SELECTED_COMPANY",
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    LOG_OUT_USER: 'LOG_OUT_USER',
    AUTHENTICATE_LOGIN_SUCCESS: 'AUTHENTICATE_LOGIN_SUCCESS',
    FETCH_CURRENCY: 'FETCH_CURRENCY',
    FETCH_DIVISION_NAME: 'FETCH_DIVISION_NAME',
    FETCH_PAYROLLS: 'FETCH_PAYROLLS',
    FETCH_EXPORT_PREFIXES: 'FETCH_EXPORT_PREFIXES'
};

export const companyActionTypes = {
    SHOW_HIDE_PANEL: 'SHOW_HIDE_PANEL',
    FETCH_COMPANY_DATALIST: 'FETCH_COMPANY_DATALIST',
    SELECTED_COMPANY_CODE: 'SELECTED_COMAPNY_CODE',
    CLEAR_SEARCH_DATA: 'CLEAR_SEARCH_DATA',
    FETCH_COMPANY_DATA: 'FETCH_COMPANY_DATA',
    ADD_COMPANY_OFFICE: 'ADD_COMPANY_OFFICE',
    ADD_EXPECTED_MARGIN: 'ADD_EXPECTED_MARGIN',
    UPDATE_COMPANY_OFFICE: 'UPDATE_COMPANY_OFFICE',
    UPDATE_EXPECTED_MARGIN: 'UPDATE_EXPECTED_MARGIN',
    DELETE_COMPANY_OFFICES: 'DELETE_COMPANY_OFFICES',
    SAVE_COMPANY_DETAILS: 'SAVE_COMPANY_DETAILS',
    DELETE_EXPECTED_MARGIN: 'DELETE_EXPECTED_MARGIN',
    EDIT_COMPANY_OFFICE: 'EDIT_COMPANY_OFFICE',
    EDIT_EXPECTED_MARGIN: 'EDIT_EXPECTED_MARGIN',
    GRID_PROPS: 'GRID_PROPS',
    SECOND_GRID_PROPS: 'SECOND_GRID_PROPS',
    STATE: 'STATE',
    CITY: 'CITY',
    BUSINESS_UNIT: 'BUSINESS_UNIT',
    COUNTRY: 'COUNTRY',
    TAX: 'TAX',
    SALUTATION: 'SALUTATION',
    VAT_PREFIX: 'VAT_PREFIX',
    COMPANY_VAT_PREFIX: 'COMPANY_VAT_PREFIX',
    SHOWBUTTON: 'SHOWBUTTON',
    FETCH_COMPANY_CONTRACT: 'FETCH_COMPANY_CONTRACT',
    FETCH_COMPANY_EXPECTED_MARGIN: 'FETCH_COMPANY_EXPECTED_MARGIN',
    FETCH_COMPANY_OFFICES:'FETCH_COMPANY_OFFICES',

    //document
    ADD_COMPANY_DOCUMENTS_DETAILS: 'ADD_COMPANY_DOCUMENTS_DETAILS',
    COPY_DOCUMENTS_DETAILS: 'COPY_DOCUMENTS_DETAILS',
    DELETE_DOCUMENTS_DETAILS: 'DELETE_DOCUMENTS_DETAILS',
    EDIT_DOCUMENTS_DETAILS: 'EDIT_DOCUMENTS_DETAILS',
    UPDATE_COMPANY_DOCUMENTS_DETAILS: 'UPDATE_COMPANY_DOCUMENTS_DETAILS',
    FETCH_DOCUMENT_TYPES: 'FETCH_DOCUMENT_TYPES',
    DISPLAY_COMPANY_DOCUMENTS: 'DISPLAY_COMPANY_DOCUMENTS',

    //General Details Action Constants
    FETCH_COMPANY_DETAILS: 'FETCH_COMPANY_DETAILS',
    FETCH_INVOICE_REMITTANCE: 'FETCH_INVOICE_REMITTANCE',
    FETCH_INVOICE_FOOTER: 'FETCH_INVOICE_FOOTER',
    ADD_INVOICE_REMITTANCE: 'ADD_INVOICE_REMITTANCE',
    ADD_INVOICE_FOOTER: 'ADD_INVOICE_FOOTER',
    EDIT_INVOICE_REMITTANCE: 'EDIT_INVOICE_REMITTANCE',
    EDIT_INVOICE_FOOTER: 'EDIT_INVOICE_FOOTER',
    UPDATE_INVOICE_REMITTANCE: 'UPDATE_INVOICE_REMITTANCE',
    UPDATE_INVOICE_FOOTER: 'UPDATE_INVOICE_FOOTER',
    DELETE_INVOICE_REMITTANCE: 'DELETE_INVOICE_REMITTANCE',
    DELETE_INVOICE_FOOTER: 'DELETE_INVOICE_FOOTER',

    //Division Cost Center Margin
    FETCH_COMPANY_DIVISION: "FETCH COMPANY DIVISION",
    FETCH_DIVISION_COST_CENTER: "FETCH DIVISION COST CENTER",
    ADD_NEW_DIVISION: 'ADD_NEW_DIVISION',
    ADD_NEW_DIVISION_COST_CENTRE: 'ADD_NEW_DIVISION_COST_CENTRE',
    EDIT_COMPANY_DIVISION: 'EDIT_COMPANY_DIVISION',
    UPDATE_COMPANY_DIVISION_BUTTON: 'UPDATE_COMPANY_DIVISION_BUTTON',
    UPDATE_COST_CENTRE_BUTTON: 'UPDATE_COST_CENTRE_BUTTON',
    UPDATE_COMPANY_DIVISION: 'UPDATE_COMPANY_DIVISION',
    DELETE_COMPANY_DIVISION: 'DELETE_COMPANY_DIVISION',
    EDIT_COMPANY_DIVISION_COST_CENTER: 'EDIT_COMPANY_DIVISION_COST_CENTER',
    UPDATE_COMPANY_DIVISION_COST_CENTER: 'UPDATE_COMPANY_DIVISION_COST_CENTER',
    DELETE_DIVISION_COST_CENTRE: 'DELETE_DIVISION_COST_CENTRE',
    //Notes
    ADD_COMPANY_NOTE: 'ADD_COMPANY_NOTE',
    UPDATE_COMPANY_NOTE: 'UPDATE_COMPANY_NOTE',
    DELETE_COMPANY_NOTE: 'DELETE_COMPANY_NOTE',
    EDIT_COMPANY_NOTE: 'EDIT_COMPANY_NOTE',

    //Payroll
    FETCH_PAYROLL_DATA: 'FETCH_PAYROLL_DATA',
    FETCH_PAYROLL_PERIOD_NAME: 'FETCH_PAYROLL_PERIOD_NAME',
    ADD_NEW_PAYROLL: 'ADD_NEW_PAYROLL',
    ADD_NEW_PAYROLL_PERIOD_NAME: 'ADD_NEW_PAYROLL_PERIOD_NAME',
    FETCH_COST_SALE_REFERENCE: 'FETCH_COST_SALE_REFERENCE',
    PAYROLL_POPUP_CLEAR: 'PAYROLL_POPUP_CLEAR',
    DELETE_PAYROLL_TYPE: 'DELETE_PAYROLL_TYPE',
    UPDATE_COMPANY_PAYROLL_BUTTON: 'UPDATE_COMPANY_PAYROLL_BUTTON',
    UPDATE_COMPANY_PAYROLL: 'UPDATE_COMPANY_PAYROLL',
    ADD_NEWPAYROLL_PERIOD_NAME: 'ADD_NEWPAYROLL_PERIOD_NAME',
    EDIT_PAYROLL_PERIOD_NAME: 'EDIT_PAYROLL_PERIOD_NAME',
    UPADTE_PAYROLL_PERIOD_NAME: 'UPADTE_PAYROLL_PERIOD_NAME',
    DELETE_PAYROLL_PERIOD_NAME: 'DELETE_PAYROLL_PERIOD_NAME',
    TOGGLE_SUBMIT_BUTTON: 'TOGGLE_SUBMIT_BUTTON',
    UPDATE_OVERRIDE_COST_SALE_REFERENCE: 'UPDATE_OVERRIDE_COST_SALE_REFERENCE',

    //Email Template
    UPDATE_EMAIL_TEMPLATE: 'UPDATE_EMAIL_TEMPLATE',
    UPDATE_EMAIL_TEMPLATE_TYPE: 'UPDATE_EMAIL_TEMPLATE_TYPE',
    UPDATE_COMPANY_EMAIL_TEMPLATE: 'UPDATE_COMPANY_EMAIL_TEMPLATE',
    FETCH_PLACEHOLDERS: 'FETCH_PLACEHOLDERS',
    //Company Taxes
    ADD_COMPANY_TAXES: 'ADD_COMPANY_TAXES',
    EDIT_COMPANY_TAXES: 'EDIT_COMPANY_TAXES',
    UPDATE_COMPANY_TAXES: 'UPDATE_COMPANY_TAXES',
    DELETE_COMPANY_TAXES: 'DELETE_COMPANY_TAXES',
    // Save
    COMPANY_UPDATED: 'COMPANY_UPDATED',

    //Company Info
    ADD_UPDATE_COMPANY_INFO: 'ADD_UPDATE_COMPANY_INFO',

    //Invoice Defaults
    ADD_UPDATE_INVOICE_DEFAULTS: 'ADD_UPDATE_INVOICE_DEFAULTS',

    //email template select value
    ONE: 'CRN',
    TWO: 'CDR',
    THREE: 'RJVT',
    FOUR: 'VCECO',
    FIVE: 'ICAOCO',

    CLEAR_STATE_CITY_DATA: 'CLEAR_STATE_CITY_DATA',
    CLEAR_COMPANY_DETAILS: 'CLEAR_COMPANY_DETAILS'
};

export const customerActionTypes = {
    FETCH_CUSTOMER_LIST: 'FETCH_CUSTOMER_LIST',
    FETCH_CUSTOMER_GENERAL_DATA: "FETCH_CUSTOMER_GENERAL_DATA",
    FETCH_CUSTOMER_GENERAL_ADDRESS_DATA: "FETCH_CUSTOMER_GENERAL_ADDRESS_DATA",
    FETCH_CUSTOMER_GENERAL_CONTACT_DATA: "FETCH_CUSTOMER_GENERAL_CONTACT_DATA",
    ADD_CUSTOMER_ADDRESS: "ADD_CUSTOMER_ADDRESS",
    ADD_CUSTOMER_CONTACT: "ADD_CUSTOMER_CONTACT",
    DELETE_CUSTOMER_ADDRESS: "DELETE_CUSTOMER_ADDRESS",
    DELETE_CUSTOMER_CONTACT: "DELETE_CUSTOMER_CONTACT",
    FETCH_ASSIGNMENT_REFERENCE: 'FETCH_ASSIGNMENT_REFERENCE',
    FETCH_ACCOUNT_REFERENCE: 'FETCH_ACCOUNT_REFERENCE',
    ADD_ASSIGNMENT_REFERENCE: 'ADD_ASSIGNMENT_REFERENCE',
    ADD_ACCOUNT_REFERENCE: 'ADD_ACCOUNT_REFERENCE',
    DELETE_ASSIGNMENT_REFERENCE: 'DELETE_ASSIGNMENT_REFERENCE',
    DELETE_ACCOUNT_REFERENCE: 'DELETE_ACCOUNT_REFERENCE',
    EDIT_ASSIGNMENT_REFERENCE: 'EDIT_ASSIGNMENT_REFERENCE',
    EDIT_CONTACT_REFERENCE: 'EDIT_CONTACT_REFERENCE',
    EDIT_ACCOUNT_REFERENCE: 'EDIT_ACCOUNT_REFERENCE',
    EDIT_ADDRESS_REFERENCE: 'EDIT_ADDRESS_REFERENCE',
    UPDATE_ADDRESS_REFERENCE: 'UPDATE_ADDRESS_REFERENCE',
    UPDATE_CONTACT_REFERENCE: 'UPDATE_CONTACT_REFERENCE,',
    UPDATE_ASSIGNMENT_REFERENCE: 'UPDATE_ASSIGNMENT_REFERENCE',
    UPDATE_ACCOUNT_REFERENCE: 'UPDATE_ACCOUNT_REFERENCE',
    FETCH_NOTES_DETAILS: 'FETCH_NOTES_DETAILS',
    ADD_NOTES_DETAILS: 'ADD_NOTES_DETAILS',
    UPDATE_NOTES_DETAILS: 'UPDATE_NOTES_DETAILS',
    DELETE_NOTES_DETAILS: 'DELETE_NOTES_DETAILS',
    EDIT_NOTES_DETAILS: 'EDIT_NOTES_DETAILS',
    FETCH_DOCUMENTS_DETAILS: 'FETCH_DOCUMENTS_DETAILS',
    ADD_DOCUMENTS_DETAILS: 'ADD_DOCUMENTS_DETAILS',
    COPY_DOCUMENTS_DETAILS: 'COPY_DOCUMENTS_DETAILS',
    DELETE_DOCUMENTS_DETAILS: 'DELETE_DOCUMENTS_DETAILS',
    UPDATE_DOCUMENTS_DETAILS: 'UPDATE_DOCUMENTS_DETAILS',
    EDIT_DOCUMENTS_DETAILS: 'EDIT_DOCUMENTS_DETAILS',
    FETCH_CUSTOMER_CONTRACT: 'FETCH_CUSTOMER_CONTRACT',
    SELECTED_CUSTOMER_CODE: 'SELECTED_CUSTOMER_CODE',
    FETCH_FILTERED_CONTRACT: 'FETCH_FILTERED_CONTRACT',
    SELECTED_CONTRACT_NUMBER: 'SELECTED_CONTRACT_NUMBER',
    FETCH_ASSIGNMENT_REF_TYPES: 'FETCH_ASSIGNMENT_REF_TYPES',
    SHOWBUTTON: 'SHOWBUTTON',
    FETCH_DOCUMENT_TYPES: 'FETCH_DOCUMENT_TYPES',
    SAVE_CUTOMER_DETAILS: 'SAVE_CUTOMER_DETAILS',
    FETCH_CUSTOMER_DETAIL: 'FETCH_CUSTOMER_DETAIL',
    FETCH_COMPANY_DOCUMENT_TYPES: 'FETCH_COMPANY_DOCUMENT_TYPES',
    SET_LOADER: 'SET_LOADER',
    REMOVE_LOADER: 'REMOVE_LOADER',
    CLEAR_SEARCH_DATA: 'CLEAR_SEARCH_DATA',
    CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
    DISPLAY_DOCUMENTS: 'DISPLAY_DOCUMENTS',
    
};

export const documentActionTypes = {
    FETCH_COMPANY_DOCUMENTS: 'FETCH_COMPANY_DOCUMENTS',
    ADD_COMPANY_DOCUMENTS: 'ADD_COMPANY_DOCUMENTS',
    UPDATE_DOCUMENTS: 'UPDATE_DOCUMENTS',
    DELETE_DOCUMENTS: 'DELETE_DOCUMENTS',
    GET_DOCUMENTS_TO_UPDATE: 'GET_DOCUMENTS_TO_UPDATE',
    FETCH_DOCUMENT_TYPES: 'FETCH_DOCUMENT_TYPES'
};
//contract Action rtypes
export const contractActionTypes={
    commonActionTypes:{
        FETCH_CONTRACT_DATA:'FETCH_CONTRACT_DATA',
        SET_CONTRACT_DATA:'SET_CONTRACT_DATA',
        UPDATE_INTERACTION_MODE:'UPDATE_INTERACTION_MODE'
    },
    SELECTED_CONTRACT_NUMBER:'SELECTED_CONTRACT_NUMBER',
    FETCH_DOCUMENT_TYPES:'FETCH_DOCUMENT_TYPES',
    FETCH_CONTRACT_DOCUMENTS:'FETCH_CONTRACT_DOCUMENTS',
    COPY_DOCUMENTS_DETAILS:'COPY_DOCUMENTS_DETAILS',
    PASTE_CONTRACT_DOCUMENTS_DETAILS:'PASTE_CONTRACT_DOCUMENTS_DETAILS',
    ADD_CONTRACT_DOCUMENTS_DETAILS:'ADD_CONTRACT_DOCUMENTS_DETAILS',
    DELETE_CONTRACT_DOCUMENTS_DETAILS:'DELETE_CONTRACT_DOCUMENTS_DETAILS',
    EDIT_DOCUMENTS_DETAILS:'EDIT_DOCUMENTS_DETAILS',
    UPDATE_CONTRACT_DOCUMENTS_DETAILS:'UPDATE_CONTRACT_DOCUMENTS_DETAILS',
    DISPLAY_CONTRACT_DOCUMENTS:'DISPLAY_CONTRACT_DOCUMENTS',
    DOWNLOAD_DOCUMENTS_DATA:'DOWNLOAD_DOCUMENTS_DATA',
    DOWNLOAD_UPLOAD_DOCUMENTS_DATA:'DOWNLOAD_UPLOAD_DOCUMENTS_DATA',
    SHOWBUTTON:'SHOWBUTTON',
    //For Notes
    FETCH_CONTRACT_NOTES:'FETCH_CONTRACT_NOTES',
    ADD_CONTRACT_NOTE:'ADD_CONTRACT_NOTE',
    //For Project
    FETCH_CONTRACT_PROJECTS:'FETCH_CONTRACT_PROJECTS',
    FETCH_CONTRACT_FIXEDRATE:"FETCH_CONTRACT_FIXEDRATE",
    ADD_FIXED_EXHCHANGE_RATE:'ADD_FIXED_EXCHANGE_RATE',
    EDIT_FIXED_EXCHANGE_RATE:'EDIT_FIXED_EXCHANGE_RATE',
    UPDATE_FIXED_EXCHANGE_RATE: 'UPDATE_FIXED_EXCHANGE_RATE',
    DELETE_FIXED_EXCHANGE_RATE:'DELETE_FIXED_EXCHANGE_RATE',
    FETCH_CURRENCY:'FETCH_CURRENCY',
    SHOW_FIXED_MODAL:'SHOW_FIXED_MODAL',
    HIDE_FIXED_MODAL:'HIDE_FIXED_MODAL',
    FETCH_CONTRACT_NOTE:'FETCH_CONTRACT_NOTE',
    SELECTED_CUSTOMER_NAME: 'SELECTED_CUSTOMER_NAME',
    SHOW_HIDE_PANEL: 'SHOW_HIDE_PANEL',
    FETCH_CUSTOMER_CONTRACT: 'FETCH_CUSTOMER_CONTRACT',
    CLEAR_SEARCH_DATA: 'CLEAR_SEARCH_DATA',
    SELECTED_CUSTOMER_CODE: 'SELECTED_CUSTOMER_CODE',
    
    /**
  * Rate Schedule Action Types
  */
    rateScheduleActionTypes:{
        IS_RATESCHEDULE_EDIT:'IS_RATESCHEDULE_EDIT',
        IS_CHARGETYPE_EDIT:'IS_CHARGETYPE_EDIT',
        IS_RATESCHEDULE_OPEN:'IS_RATESCHEDULE_OPEN',
        IS_CHARGETYPE_OPEN:'IS_CHARGETYPE_OPEN',
        FETCH_RATE_SCHEDULE:'FETCH_RATE_SCHEDULE',
        ADD_RATE_SCHEDULE:'ADD_RATE_SCHEDULE',
        ADD_CHARGE_TYPE:'ADD_CHARGE_TYPE',
        EDIT_CHARGE_TYPE:'EDIT_CHARGE_TYPE',
        EDIT_RATE_SCHEDULE:'EDIT_RATE_SCHEDULE',
        UPDATE_RATE_SCHEDULE:'UPDATE_RATE_SCHEDULE',
        UPDATE_CHARGE_TYPE:'UPDATE_CHARGE_TYPE',
        DELETE_RATE_SCHEDULE:'DELETE_RATE_SCHEDULE',
        DELETE_CHARGE_TYPE:'DELETE_CHARGE_TYPE'
    },
    invoiceDefaultActionTypes: {
        ADD_NEW_INVOICE_DEFAULT: 'ADD_NEW_INVOICE_DEFAULT',
        DELETE_INVOICE_DEFAULT: 'DELETE_INVOICE_DEFAULT',
        ADD_ATTACHMENT_TYPES: 'ADD_ATTACHMENT_TYPES',
        DELETE_ATTACHMENT_TYPES: 'DELETE_ATTACHMENT_TYPES',
        SHOW_CUSTOMER_CONTACT: 'SHOW_CUSTOMER_CONTACT',
        SHOW_SALES_TAX: 'SHOW_SALES_TAX',
        SHOW_WITHOLDING_TAX: 'SHOW_WITHOLDING_TAX',
        SHOW_INVOICE_PAYMENT_TERMS: 'SHOW_INVOICE_PAYMENT_TERMS',
        SHOW_CUSTOMER_CONTRACT_ADDRESS: 'SHOW_CUSTOMER_CONTRACT_ADDRESS',
        SHOW_INVOICE_CURRENCY: 'SHOW_INVOICE_CURRENCY',
        SHOW_INVOICE_GROUPING: 'SHOW_INVOICE_GROUPING',
        SHOW_INVOICE_REMITTANCE_TEXT: 'SHOW_INVOICE_REMITTANCE_TEXT',
        SHOW_INVOICE_FOOTER: 'SHOW_INVOICE_FOOTER',
        SHOW_DEFAULT_INVOICE_REFERENCES: 'SHOW_DEFAULT_INVOICE_REFERENCES',
        SHOW_DEFAULT_INVOICE_ATTACHMENT_TYPES: 'SHOW_DEFAULT_INVOICE_ATTACHMENT_TYPES',
        SHOW_REFERENCE_TYPE: 'SHOW_REFERENCE_TYPE',
        SHOW_INVOICE_DEFAULT_MODAL: 'SHOW_INVOICE_DEFAULT_MODAL',
        HIDE_INVOICE_DEFAULT_MODAL: 'HIDE_INVOICE_DEFAULT_MODAL',
        IS_INVOICE_REFERENCE_MODAL_OPEN: 'IS_INVOICE_REFERENCE_MODAL_OPEN',
        IS_INVOICE_REFERENCE_EDIT: 'IS_INVOICE_REFERENCE_EDIT',
        CONTRACT_DOCUMENT_TYPE_MASTER: 'CONTRACT_DOCUMENT_TYPE_MASTER',
        IS_INVOICE_ATTACHMENT_TYPES_MODAL_OPEN: 'IS_INVOICE_ATTACHMENT_TYPES_MODAL_OPEN',
        IS_INVOICE_ATTACHMENT_TYPES_EDIT: 'IS_INVOICE_ATTACHMENT_TYPES_EDIT',
    }  
};

//Modal Action Types
export const modalActionTypes = {
    DISPLAY_MODAL: 'DISPLAY_MODAL',
    HIDE_MODAL: 'HIDE_MODAL',
    TOGGLE_MODAL_STATE: 'TOGGLE_MODAL_STATE'
};

export const loginActionTypes = {
    AUTHENTICATE_LOGIN_FAILED: 'AUTHENTICATE_LOGIN_FAILED',
    AUTHENTICATE_LOGIN_SUCCESS: 'AUTHENTICATE_LOGIN_SUCCESS',
    TOKEN_STORAGE: 'TOKEN_STORAGE'
};
